name: PaperInvisiframes
version: ${project.version}
api-version: 1.20
main: eu.b1o.mc.paperinvisiframes.PaperInvisiframes
author: Techdoodle & Link_1503
folia-supported: true
commands:
  iframe:
    permission: paperinvisiframes.cmd
    description: Base command for PaperInvisiframes
    usage: /iframe <reload|force-recheck>
permissions:
  paperinvisiframes.place:
    default: true
  paperinvisiframes.craft:
    default: true
  paperinvisiframes.cmd:
    default: op
  paperinvisiframes.reload:
    default: op
  paperinvisiframes.forcerecheck:
    default: op
  paperinvisiframes.get:
    default: op